# Site settings
title: Ivan Premgi's CV
description: Ivan Premgi's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ipremgi-com.github.io/
url: https://ipremgi-com.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ivan Premgi
  title: Software Enginner
  address: London, United Kingdom
  email: ivan@ivanpremgi.com
  link: http://ivanpremgi.com
  weibo:
  # github: 
  linkedin: ivan-premgi-b6194ba2
  # twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Capgemini UK Plc
      location: London, United Kingdom
      title: Java Developer
      started: 2015
      duration: (2015 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Capgemini UK Plc
      location: London, United Kingdom
      title: Developer
      started: 2014
      duration: (2014 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Kumon
      location: London, United Kingdom
      title: Maths Assistant
      started: 2013
      duration: (2013 - 2014)
      description: dkdkdkkdkkdkkdk
        xfdf
     - work4:
      company: Capgemini UK Plc
      location: London, United Kingdom
      title: Java Developer
      started: 2015
      duration: (2015 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    
  educationHistory:
    - education1:
      organization: Aston University
      location: Birmingham, United Kingdom
      degree: Bachelor of Science
      major: Digital & Technology Solutions
      started: 2016
      duration: (2016 - 2019)
      description: Need to ADD
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Gujarati
      proficiency: Novice
  programmingSkills:
    - skill1:
      name: Java
      percentage: 60%
    - skill2:
      name: Scala
      percentage: 10%
    - skill3:
      name: Spring
      percentage: 20%
    - skill4:
      name: SQL
      percentage: 40%
    - skill5:
      name: Korn Shell
      percentage: 30%
      
